name: micro_home
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  micro_core:
    path: ../micro_core
  
  base_ui:
    path: ../base_ui
      
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true