name: micro_home
description: A new Flutter package project.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  micro_core:
    git:
      url: https://github.com/gusttavovianna/micro_core.git
      ref: v1.0.0
  
  base_ui:
    git:
      url: https://github.com/gusttavovianna/base_ui.git
      ref: v1.0.0 
      

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true